.TH ADD-SHELL 8 "12 May 2011"
.SH NAME
add-shell \- add shells to the list of valid login shells
.SH SYNOPSIS
.B  add-shell
.I  shellname
.RI [ shellname ...]
.SH DESCRIPTION
.B add-shell
copies \fI/etc/shells\fR to \fI/etc/shells.tmp\fR, adds the given shells to
this file if they are not already present, and copies this temporary file
back to \fI/etc/shells\fR.

The shells must be provided by their full pathnames.
.SH "SEE ALSO"
.BR shells (5)
