.TH INSTALLKERNEL 8 "7 Jan 2001" "Debian Linux"
.SH NAME
installkernel \- install a new kernel image
.SH SYNOPSYS
.BI "installkernel " "version zImage System.map [directory]"
.SH DESCRIPTION
.PP
.B installkernel
installs a new kernel image onto the system from the Linux source
tree.  It is called by the Linux kernel makefiles when
.B make install
is invoked there.
.P
The new kernel is installed into
.IR {directory}/vmlinuz-{version} ,
a link is made from
.I {directory}/vmlinuz
to the new kernel, and the previously installed kernel is available as
.IR {directory}/vmlinuz.old .
If you use LILO, 
.I /etc/lilo.conf
should contain entries for the images
.IR {directory}/vmlinuz " and " {directory}/vmlinuz.old .
.RI ( {version}
is the new kernel's version.)
.P
.B installkernel
calls
.B mkboot -i
to make the system bootable after the kernel is installed.
.SH BUGS
installkernel resides in /sbin only because the Linux kernel makefiles
call it from there.  It should really be in /usr/sbin.  It isn't
needed to boot a system, and it calls
.BR mkboot ,
which depends on the /usr partition being mounted.
.SH "SEE ALSO"
mkboot(8), lilo(8), lilo.conf(5)
