.TH MKBOOT 8 "18 September 2004" "Debian"
.SH NAME
mkboot \- makes a bootdisk
.SH SYNOPSIS
.B "mkboot [\-r rootpartition] [\-i] [\-d device] [kernel]"
.SH DESCRIPTION
.PP
.B mkboot
makes a bootdisk.
.P
By default the bootdisk will use the kernel
.I /vmlinuz
and the current root partition.  Use the
.B \-r
option to specify a different partition, and provide the new kernel
file directly to specify a different kernel.  Use the
.B \-d
option to specify a different device for the floppy drive.
.P
If invoked with the
.B \-i
option, it tries to make a Debian GNU/Linux system bootable after a new
kernel was installed by
.BR "/sbin/installkernel" "."
If ELILO is installed, it runs
.BR "/usr/sbin/elilo" "."
If GRUB is installed, it does nothing.  If LILO is in use, it runs
.BR "/sbin/lilo" "."
If SILO is installed, it does nothing.
Otherwise, 
.B mkboot
will make a new bootdisk.
.SH "BUGS"
.P
mkboot only works on i386 and ia64.  mkboot only works
on floppy diskette drives.  If rdev is not present, mkboot will fail to
determine the correct root partition.
Patches to correct these deficiencies are welcome.
.P
.SH "SEE ALSO"
installkernel(8), lilo(8), grub(8), silo(8)
