#! /bin/sh

set -e

case "$1" in
    remove|purge|upgrade|deconfigure|disappear)
    if which update-mime >/dev/null;
    then
            update-mime
    fi
        ;;
    failed-upgrade|abort-install|abort-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
