.\"Traduction Lundi 13 janvier 2003 par Antoine Gémis
.\"(agemis@netuup.com)
.\"(savelog 1.16.7) 
.TH SAVELOG 8 "12 avril 2003" "Debian GNU/Linux"
.SH NOM
savelog \- sauvegarde un fichier journal
.SH SYNOPSIS
.B savelog
[\-m mode] [\-u utilisateur] [\-g groupe] [\-t] [\-p] [\-c cycle] [\-l] [\-j]
[\-C] [\-d] [\-l] [\-r répertoire] [\-n] [\-q] fichier...
.SH DESCRIPTION
Le programme
.B savelog
sauvegarde un fichier journal et éventuellement, compresse
les anciens fichiers. Les anciennes versions de 
.I fichier
sont renommées\ :
.RS

.IR "fichier" "." "<numéro>" "" "<extension_de_compression>"

.RE
ou
.I <numéro>
est le numéro de version, la version la plus récente portant le numéro 0. Si
l'option
.B \-l 
n'est pas spécifiée, les versions dont le numéro
est > 0 sont compressées.
La version 0 n'est pas compressée car le
.I fichier
est peut-être utilisé par un programme. 
L'argument 
.I cycle
indique le nombre de versions à conserver.

Si le fichier n'existe pas et que l'option 
.B \-t
est utilisée, le fichier est créé.

Les actions suivantes sont effectuées pour les fichiers existants, dont la taille
est supérieure à zéro\ :

.IP 1)
La version change, le fichier de version
.IR cycle \-2
est renommé version
.IR cycle "\-3,"
la version
.IR cycle \-1
est renommée version
.IR cycle "\-2 ,"
et ainsi de suite. Finalement, la version 0 est renommée version 1 et la 
version
.I cycle
est supprimée. Même en spécifiant l'option 
.BR \-l ,
les fichiers compressés et non 
compressés sont renommés.
Les versions manquantes sont ignorées.

.IP 2)
Le nouveau
.I fichier.1
est compressé sauf si l'option 
.B \-l
est utilisée. Il est modifié en tenant compte des arguments des options
.BR "\-m" ", " "\-u" ", et " "\-g" .
.

.IP 3)
Le fichier principal est renommé 
.IR fichier.0 .

.IP 4)
Si les options
.BR "\-m" ", " "\-u" ", " "\-g" ",  " "\-t" ", ou " "\-p"
sont utilisées, alors un 
.I fichier
vide est créé en tenant compte des arguments de ces options.
En utilisant l'option
.B \-p
, le fichier est créé avec le même utilisateur, groupe et permissions que 
l'ancien fichier.

.IP 5)
Le nouveau
.I fichier.0
est modifié en fonction des arguments des options
.BR "-m" ", " "-u" ", et " "-g" .

Comme le numéro de version commence à 0, 
.I cycle
n'est jamais atteint.  La valeur de 
.I cycle
doit être supérieure ou égale à 2.

.SH OPTIONS
.TP
.B "\-m mode"
Modifie les autorisations d'accès des fichiers journaux (chmod mode).
.TP
.B "\-u utilisateur"
Attribue les fichiers journaux à utilisateur (chown utilisateur).
.TP
.B "\-g groupe"
Attribue les fichiers journaux au groupe groupe (chgrp groupe).
.TP
.B "\-c cycle"
Sauvegarde cycle versions du fichier journal (7 par défaut).
.TP
.B \-t
Si nécessaire, crée le fichier journal.
.TP
.B \-l
Ne compresse pas les fichiers journaux (par défaut, les fichiers sont
compressés).
.TP
.B \-p
Conserve le propriétaire, le groupe et les permissions du fichier journal.
.TP                                                                             
.B \-j                                                                          
Compresse avec bzip2 au lieu de gzip.                                             
.TP                                                                             
.B \-C                                                                          
Force la suppression des sauvegardes.                                                
.TP                                                                             
.B \-d                                                                          
Utilise la date (YYMMDDhhmmss) au lieu du numéro de version.
.TP                                                                             
.B \-r                                                                          
Sauvegarde les fichiers journaux dans le répertoire
.I répertoire                                                                      
au lieu de .                                                       
.TP                                                                             
.B \-n                                                                          
Ne sauvegarde pas les fichiers vides.
.TP                                                                             
.B \-q                                                                          
N'affiche pas de message.      

.SH BOGUES
Si un programme est en train d'écrire 
.IR "fichier.0" ","
et que savelog le renomme
.I fichier.1
et le compresse, des données peuvent être perdues.
.SH TRADUCTION
Antoine Gémis <agemis@netuup.com>.
